In [1]:
import pandas as pd
import numpy as np

In [3]:
customers = pd.read_csv("/Users/siddhiwanzkhade/Downloads/datasets/olist_customers_dataset.csv")
orders = pd.read_csv("/Users/siddhiwanzkhade/Downloads/datasets/olist_orders_dataset.csv")
order_items = pd.read_csv("/Users/siddhiwanzkhade/Downloads/datasets/olist_order_items_dataset.csv")
order_payments = pd.read_csv("/Users/siddhiwanzkhade/Downloads/datasets/olist_order_payments_dataset.csv")

# (load later if needed)
products = pd.read_csv("/Users/siddhiwanzkhade/Downloads/datasets/olist_products_dataset.csv")
order_reviews = pd.read_csv("/Users/siddhiwanzkhade/Downloads/datasets/olist_order_reviews_dataset.csv")
sellers = pd.read_csv("/Users/siddhiwanzkhade/Downloads/datasets/olist_sellers_dataset.csv")

In [4]:
print(customers.shape)
print(orders.shape)
print(order_items.shape)
print(order_payments.shape)

(99441, 5)
(99441, 8)
(112650, 7)
(103886, 5)

In [6]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [16]:
customers.isnull().sum()
orders.isnull().sum()
order_items.isnull().sum()
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [9]:
#checking  weather customer_id is unique
customers["customer_id"].nunique()
orders["customer_id"].nunique()

99441

In [11]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [12]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [13]:
customers.describe(include='all')

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

In [14]:
orders.info()
order_items.info()
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [17]:
#checking if 1 customer has multiple orders
orders.groupby("customer_id")["order_id"].count().head()

customer_id
00012a2ce6f8dcda20d059ce98491703    1
000161a058600d5901f007fab4c27140    1
0001fd6190edaaf884bcaf3d49edf079    1
0002414f95344307404f0ace7a26f1d5    1
000379cdec625522490c315e70c7a9fb    1
Name: order_id, dtype: int64

In [20]:
orders.groupby("customer_id")["order_id"].count().value_counts().sort_index()

order_id
1    99441
Name: count, dtype: int64

In [22]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [24]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [25]:
orders = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

In [26]:
orders.groupby("customer_unique_id")["order_id"].count().value_counts()

order_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [27]:
#aggregating payments
payments_agg = order_payments.groupby("order_id", as_index=False).agg({
    "payment_value": "sum",
    "payment_installments": "max"
})

In [28]:
#merging orders + items
orders_items = orders.merge(order_items, on="order_id", how="left")

In [29]:
#add payments 
orders_items_pay = orders_items.merge(payments_agg, on="order_id", how="left")

In [30]:
orders_items_pay.head()
orders_items_pay.shape

(113425, 17)

In [31]:
#CREATING USER LEVEL DATASET
user_df = orders_items_pay.groupby("customer_unique_id").agg({
    "order_id": "nunique",        # total orders
    "payment_value": "sum",       # total spend
    "price": "mean",              # avg price
    "order_item_id": "count"      # total items
}).reset_index()

In [32]:
#renameing columns
user_df.columns = [
    "customer_unique_id",
    "total_orders",
    "total_spent",
    "avg_price",
    "total_items"
]

In [33]:
user_df["avg_order_value"] = user_df["total_spent"] / user_df["total_orders"]

In [44]:
#fixing date dtype
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders_items_pay[col] = pd.to_datetime(orders_items_pay[col])

In [48]:
#how recently a user bought something
last_purchase = orders_items_pay.groupby("customer_unique_id")["order_purchase_timestamp"].max()

user_df["days_since_last_purchase"] = user_df["customer_unique_id"].map(
    (orders_items_pay["order_purchase_timestamp"].max() - last_purchase).dt.days
)

In [49]:
#tenure(how long the user has been active )
first_purchase = orders_items_pay.groupby("customer_unique_id")["order_purchase_timestamp"].min()

user_df["customer_tenure_days"] = user_df["customer_unique_id"].map(
    (orders_items_pay["order_purchase_timestamp"].max() - first_purchase).dt.days
)

In [50]:
user_df.head()

,customer_unique_id,total_orders,total_spent,avg_price,total_items,avg_order_value,days_since_last_purchase,customer_tenure_days
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,129.90,1,141.90,160,160
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,18.90,1,27.19,163,163
2,0000f46a3911fa3c0805444483337064,1,86.22,69.00,1,86.22,585,585
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,25.99,1,43.62,369,369
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,180.00,1,196.89,336,336

In [51]:
orders_items_pay["order_purchase_timestamp"].dtype

dtype('<M8[ns]')

In [52]:
orders_items_pay["order_purchase_timestamp"].dtype

dtype('<M8[ns]')

In [53]:
orders_items_pay["order_purchase_timestamp"].dtype

dtype('<M8[ns]')

In [55]:
user_df[["days_since_last_purchase", "customer_tenure_days"]].isnull().sum()

days_since_last_purchase    0
customer_tenure_days        0
dtype: int64

In [56]:
user_df[["days_since_last_purchase", "customer_tenure_days"]].describe()

       days_since_last_purchase  customer_tenure_days
count              96096.000000          96096.000000
mean                 287.735691            290.458552
std                  153.414676            153.903666
min                    0.000000              0.000000
25%                  163.000000            166.000000
50%                  268.000000            272.000000
75%                  397.000000            400.000000
max                  772.000000            772.000000

### CREATING TARGET VARIABLE SO THAT MODEL CAN LEARN PATTERNS

In [61]:
#REFERENCE DATE(WICH ACTS LIKE TODAY)
max_date = orders_items_pay["order_purchase_timestamp"].max()

In [62]:
#LAST PURCHASE DATE PER USER
last_purchase = orders_items_pay.groupby("customer_unique_id")[
    "order_purchase_timestamp"
].max().reset_index()

In [87]:
#CREATE TARGET (labels users as 1 if they purchased in last 90 days , else 0)
last_purchase["target_90d"] = (
    (max_date - last_purchase["order_purchase_timestamp"]).dt.days <= 90
).astype(int)

In [73]:
#merge the target variable into user_df
user_df = user_df.merge(
    last_purchase[["customer_unique_id", "target_90d"]],
    on="customer_unique_id",
    how="left"
)

In [77]:
#filling missing na
user_df["target_90d"] = user_df["target_90d"].fillna(0)

In [75]:
user_df["target_90d"].value_counts()

target_90d
0    86432
1     9664
Name: count, dtype: int64

In [76]:
user_df["target_90d"].isna().sum()

np.int64(0)

In [78]:
user_df.head()

,customer_unique_id,total_orders,total_spent,avg_price,total_items,avg_order_value,days_since_last_purchase,customer_tenure_days,target_30d,target_90d
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,129.90,1,141.90,160,160,0,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,18.90,1,27.19,163,163,0,0
2,0000f46a3911fa3c0805444483337064,1,86.22,69.00,1,86.22,585,585,0,0
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,25.99,1,43.62,369,369,0,0
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,180.00,1,196.89,336,336,0,0

In [88]:
user_df["target_90d"].tail(20)

96076    0
96077    0
96078    0
96079    0
96080    0
96081    0
96082    1
96083    0
96084    0
96085    0
96086    1
96087    0
96088    0
96089    0
96090    0
96091    0
96092    0
96093    0
96094    0
96095    0
Name: target_90d, dtype: int64

In [85]:
user_df["target_90d"].value_counts()

target_90d
0    86432
1     9664
Name: count, dtype: int64

In [86]:
user_df["target_90d"].unique()

array([0, 1])

In [91]:
user_df.to_csv("final_df.csv", index=False)

In [92]:
user_df.to_pickle("final_df.pkl")

In [94]:
df = pd.read_pickle("final_df.pkl")

In [95]:
df

,customer_unique_id,total_orders,total_spent,avg_price,total_items,avg_order_value,days_since_last_purchase,customer_tenure_days,target_30d,target_90d
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,129.90,1,141.90,160,160,0,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,18.90,1,27.19,163,163,0,0
2,0000f46a3911fa3c0805444483337064,1,86.22,69.00,1,86.22,585,585,0,0
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,25.99,1,43.62,369,369,0,0
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,180.00,1,196.89,336,336,0,0
...,...,...,...,...,...,...,...,...,...,...
96091,fffcf5a5ff07b0908bd4e2dbc735a684,1,4134.84,785.00,2,4134.84,495,495,0,0
96092,fffea47cd6d3cc0a88bd621562a9d061,1,84.58,64.89,1,84.58,310,310,0,0
96093,ffff371b4d645b6ecea244b27531430a,1,112.46,89.90,1,112.46,617,617,0,0
96094,ffff5962728ec6157033ef9805bacc48,1,133.69,115.00,1,133.69,168,168,0,0
96095,ffffd2657e2aad2907e67c3e9daecbeb,1,71.56,56.99,1,71.56,532,532,0,0